### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RicoBytes** [McAPI/McAPI#19]
I'm using this API to check if a player is premium but... it sometimes send this message 

The service is currently cooling down and cannot perform any requests. Please try it later again.

**Comment by RicoBytes** [comment]
hey pls

**Comment by jan-krueger** [comment]
Hello,
I am sorry for the delayed answer, but I was on a holiday trip. - This message is caused by a change to the system of how we are dealing with this type of requests introduced in [Version 2.4](https://mcapi.de/changelog#v24) and it basically means that we have at this exact moment no way of requesting and serving information about this player.

It is caused by the reason that we don't have the user in our cache _and_ that we can sent no more requests to Mojang to check the status of a player, because Mojang is limiting the amount of requests to [600 per 10 minutes per IP address](http://wiki.vg/Mojang_API). We've to wait until our server provider (DigitalOcean) allows us to bind multiple IPv4 addresses to our nodes, so we can distribute our requests and avoid this limit. Another solution could be to assign multiple IPv6 addresses to our servers, but the Mojang endpoints don't support that yet.

I am sorry, but we cannot do much about that. The system is ready to expand once we are able to expand it, but we don't know when that's the case. - We've currently about 520.000 unique users in our permanent cache, and we also serve from it if we cannot make a request, so the situation should improve over time.

Regards,
Jan
