### ISSUE TITLE
Response code.

### ISSUE THREAD

**Issue by luizhtss** [McAPI/McAPI#27]
Hello, what is the response code that returns when the player is not premium?

**Comment by jan-krueger** [comment]
The response code is only in regards to whether there was an error or not (simply put). - https://mcapi.de/user the /user endpoint provides a field called "premium" that is "true" when the user has bought Minecraft and "false" when not. 

If you are building a new application I recommend to stop using the current version of mcapi.de and to move to the new 3.0 version. It is currently reachable at https://beta.mcapi.de and the documentation is available at http://docs.mcapi.de - If you use the new user API endpoint then you have to keep in mind that we are now dealing differently with user requests.

1. If you request a user but no data is available at the point in time, we will return a 202 status code indicating that we have created a new background task that will be fulfilled in the feature. 

2. If you request a user and data is available at the point in time, we will return a 200 status code indicating that data is ready to read.

I highly recommend using the beta because the old version will be discontinued in the near future. - If you have more questions please feel free to ask.

**Comment by luizhtss** [comment]
I can't use the beta version.

My url: https://beta.mcapi.de/api/user/profile/USERNAME

**Comment by jan-krueger** [comment]
What's the problem with the beta version? Do you get an error?

**Comment by luizhtss** [comment]
It worked now, you know which is the response code that returns when it gets too many request ?

**Comment by jan-krueger** [comment]
Yes, the response code is 429. The documentation isn't covering everything yet, unfortunately. but that will be soon part of it. You should consider everything outside of the 200..299 range as unsuccessful.

**Comment by luizhtss** [comment]
Thank you.
