### ISSUE TITLE
Return 429 on first request

### ISSUE THREAD

**Issue by TuxCoding** [McAPI/McAPI#9]
Recently I got a 429 although it was a new request

**Comment by jan-krueger** [comment]
Thank you for the hint. - I am currently on vacation and I have no access to a device to deploy more backbones servers. I will be back at the end of week the next week to deploy more backend servers.

**Comment by TuxCoding** [comment]
I don't think this is a issue of unavailable backbones. It's a caching issue, because I accessed

https://mcapi.de/api/user/a00e1b19d0ba4bfcaf3dbf68cf176277

for skin downloading and it worked just on the second attempt. Sorry I forgot to add the request url. Too much in hurry.

**Comment by jan-krueger** [comment]
If all servers had no requests left than the 429 is an expected result. You may caused the little time gap between no left and one server gained access again.

**Comment by TuxCoding** [comment]
Should the skin be cached for at least one minute?

I think what's hapenning here is that the api makes another name requests although I request the endpoint by uuid, because the name -> uuid requests are rate-limited by ip while skin requests are rate-limited by each individual player.

**Comment by jan-krueger** [comment]
Skins are currently stored for 48h but due to technical circumstances it's stored in a seperate cache from all other data. I may combine them in the future but this takes some implementation work. This might be an part of a major version update.  

If I expect it do be done earlier or if I find another cause for this behaviour I will update this issue but I think your point is right.

**Comment by TuxCoding** [comment]
But it looks like the caching doesn't work. Here some other examples:

https://mcapi.de/api/user/797acc9d43474f24aec4ed99eadb2fe5
https://mcapi.de/api/user/f420e4624f4b442e92106826d1e5d66c
https://mcapi.de/api/user/5f49ce71e15a4d509565d96daa93b2e3
https://mcapi.de/api/user/797acc9d43474f24aec4ed99eadb2fe5

Maybe try to debug what's the exact rate-limit is, because skin downloads are only rate-limited to one per minute **per player** instead of 600 per source ip for name -> uuid.

**Comment by TuxCoding** [comment]
Maybe you make other requests on that too which ends up in a 429.

**Comment by jan-krueger** [comment]
Well, I think I know now how to solve the problem. I just should have checked if I get a incomplete data-set and if that is the case I will just try to get a complete data-set from one of the backbones and if that fails I will set the cache time to only one minute instead of six hours to allow the client to queue his request for a minute later.

**Comment by meyerzinn** [comment]
Why don't backbone servers automatically scale? Also, couldn't we use a proxy list or such to avoid this backbone issue?

**Comment by jan-krueger** [comment]
@20zinnm To let the system scale automatically was also one of my thoughts while writing the system (https://mcapi.de/changelog#v23) but while I implemented this feature I had not enough free-time to also integrate a whole new system and I am also kinda "handicapped" as student in terms of money.

**Comment by meyerzinn** [comment]
#14 would solve the money issue.

**Comment by jan-krueger** [comment]
This issue cannot be 100% be resolved, but I do my best. I implemented a new version of the /api/user-backend (https://mcapi.de/changelog#v24) and it improved the situation extremly due to my metrics. This error can still occur, but the error rate should drop over time since I am no caching user data permanently.
